package com.positron.teachers.model

data class TeachersLogin(
    var status : Boolean? = false,
    var error: String? = null,
    var message: String? = null,
    var id: String? = null,
    var school_id: Int? = null,
    var username: String? = null,
    var employee_id: String? = null,
    var mobile_app_default_pass: String? = null,
    var email: String? = null,
    var contact_no: String? = null,
    var image: String? = null,
    var role: String? = null,
    var roles: Map<String, String>? = null,
    var token: String? = null,
    var date_format: String? = null,
    var currency_symbol: String? = null,
    var start_month: String? = null,
    var school_name: String? = null,
    var timezone: String? = null,
    var sch_name: String? = null,
    var language: Language,
    var is_rtl: String? = null,
    var theme: String? = null,
    var is_hidden: String? = null,
    var error_message: String? = null,
    val channel: String,

)